import mysql.connector

print("Username: ", end="")
usr = input()
print("Password: ", end="")
pwd = input()
print("Database: ", end="")
db = input()
conn = mysql.connector.connect(user=usr, password=pwd, host='127.0.0.1', database=db)
cursor = conn.cursor()
print("Tabella: ", end="")
tb = input()
print("Struttura tabella:\n")
cursor.execute("show columns from "+tb)
print(cursor.fetchall())
conn.close()